export * from './ir';
export * from './color';
export * from './detect';
export * from './signals';
export * from './analyze';
export * from './style/presets';
export * from './style/brief';
export * from './style/css';
export * from './consultant/discover';
export * from './consultant/patterns';
export * from './consultant/apply';
export * from './consultant/plan';
export { EMOJI_RE, itemsAreUniform } from './analyze/util';
export * from './style/verify';
